# Generated by Django 5.2.2 on 2025-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_auto_fill_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='description',
            field=models.TextField(default='joml', editable=False),
            preserve_default=False,
        ),
    ]
