name: Auto Deploy to Server

on:
  push:
    branches: [ main ]  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH Commands
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command: |
            cd /repos/schools
            git pull origin main
            poetry install --only main
            poetry run python manage.py collectstatic --noinput
            poetry run python manage.py migrate --noinput
            sudo systemctl restart gunicorn_gcischools
