name: Auto Deploy to Server

on:
  push:
    branches: [ main ]  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # Navigate to your project directory
          cd /repos/schools
          
          # Pull latest changes
          git pull origin main
          
          # Install/update dependencies
          poetry install --only main
          
          # Collect static files
          poetry run python manage.py collectstatic --noinput
          
          # Run migrations (optional but recommended)
          poetry run python manage.py migrate --noinput
          
          # Restart Gunicorn
          sudo systemctl restart gunicorn_gcischools
          
          # Optional: restart nginx if needed
          # sudo systemctl restart nginx